### ISSUE TITLE
General question: Micropython for production: is it possible to protect code

### ISSUE THREAD

**Issue by FalconBFR** [rdehuyss/micropython-ota-updater#7]
Dear rdehuyss, thanks for sharing this amazing work and also adding support for private repos. However, as a beginner to micropython who is trying to bring a product into production, I was wandering whether micropython is suitable. For instance, since code and not binary needs to be uploaded to the controller, won't that allow hackers to see the source the code / be a potential security issue? I am only trying to ask here because I think you will have great expertise on this topic. Sorry for crowding the issues section and please delete if inappropriate. Thanks so much for your kind advice in advance!

Clement

**Comment by yeyeto2788** [comment]
Hey @FalconBFR you would need to compile your scripts into `.mpy` files (https://docs.micropython.org/en/latest/reference/mpyfiles.html) I have worked on a script that does for you https://github.com/yeyeto2788/uminifier. Hope it helps.

**Comment by FalconBFR** [comment]
Thanks so much @rdehuyss for your kind help. I will try to investigate more about this on my own. So would .mpy files work with this project? Thanks so much.

**Comment by yeyeto2788** [comment]
@FalconBFR Yes, the only thing is that you need to also compile the code from this repository.

**Comment by rdehuyss** [comment]
Hi @FalconBFR , hackers can only access your code if one of the below is true:
- they have access to the device (they can then download the source code using usb access)
- they control the WIFI network where your device is connected to

Since you use a private repo and this project uses ssl encryption, it will not be easy for hackers to sniff the code from the air.

Even if it works be binary, most code can be decompiled unless it is obfuscated.
